apiVersion: v1
kind: Secret
metadata:
  name: db-credentials-secret
type: Opaque
data:
  SPRING_DATASOURCE_URL: amRiYzpteXNxbDovL3NwcmluZy1teXNxbDozMzA2L2NvbXBhbnk/Y3JlYXRlRGF0YWJhc2VJZk5vdEV4aXN0PXRydWUmY2hhcmFjdGVyRW5jb2Rpbmc9VVRGLTgmdXNlVW5pY29kZT10cnVlJnVzZVNTTD1mYWxzZSZhbGxvd1B1YmxpY0tleVJldHJpZXZhbD10cnVl
  SPRING_DATASOURCE_USERNAME: cm9vdA==
  SPRING_DATASOURCE_PASSWORD: a2FydGlrZGFuZ2k=
